name: 'Labeled Unassigned Issues Report Generator'
description: 'Generates a gist report of open, unassigned issues with at least one of the specified labels applied'
author: 'rob-derosa@github.com'
branding:
  icon: alert-triangle
  color: red
inputs:
  labels:
    required: true
    description: 'A comma delimited ordered list of required labels'
  github-token:
    required: true
    description: 'A PAT that has the ability to read repos and post gists'
outputs:
  report-url:
      description: 'A url to the generated gist report'
runs:
  using: 'node12'
  main: 'dist/index.js'