name: 'Unassigned Issues Reporter'
description: 'Generates a gist report of unassigned issues with a priority label'
author: 'rob-derosa@github.com'
branding:
  icon: alert-triangle
  color: red
inputs:
  priorities:
    required: true
    description: 'A comma delimited list of priority labels'
  github-token:
    required: true
    description: 'A PAT that has the ability to read repos and post gists'
outputs:
  report-url:
      description: 'A url to the generated gist report'
runs:
  using: 'node12'
  main: 'dist/index.js'