name: 'Generate unassigned issue report'
on:
  workflow_dispatch
jobs:
  generate-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        name: "Generate report"
        with:
          priorities: "blocker,critical,important"
          github-token: ${{ secrets.ISSUE_PAT }}